#!/usr/bin/env bash

xcodebuild -workspace ImgFlo.xcworkspace -scheme ImgFlo-Mac -sdk macosx clean test

# Tests for the iOS target pass in Xcode but fail on the command line
# xcodebuild -workspace ImgFlo.xcworkspace -scheme ImgFlo-iOS -sdk iphonesimulator clean test
